AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy single instance using jenkins"

Parameters: 

  ImageId: 
    Type: AWS::EC2::Image::Id
    Default: ami-0dc96254d5535925f
    Description: AMI ID

  HostName:
    Type: String
    MaxLength: 15
    Default: amasandmoh-1
    Description: Name of the host

  SubnetId: 
    Type: AWS::EC2::Subnet::Id
    Default : subnet-077b1394a895ba277
    Description: Subnet ID
  
  SecurityGroupIds:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-093b8019e736b90c0
    Description: Choose the default platform security group

  SystemOwner:
    Type: String
    Default: "mohammad.ayub@industry.nsw.gov.au"
    Description: Emails address of technical point of contact for the server.
      
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.micro
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
       - !Ref SecurityGroupIds
      KeyName: DOI-SANDBOX_Keypair
      BlockDeviceMappings:
        -
          DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 10
            VolumeType: gp2
      Tags:
        -
          Key: Name
          Value: !Ref HostName
        -
          Key: SystemOwner
          Value: !Ref SystemOwner